### ISSUE TITLE
this is the best seg project i saw, there is no one

### ISSUE THREAD

**Issue by zhangyunming** [cavalleria/humanseg.pytorch#2]
ruti.

刚看到这个项目，Fast scnn的训练精度是多少啊，我看到没写，我用其他的几个fast scnn工程训练自己的二类数据效果都不太好。

感谢。

**Comment by cavalleria** [comment]
thx, fastscnn result has updated

**Comment by zhangyunming** [comment]
你好，我尝试训练了 ，挺好用的
有些问题需要请教一下。

1. 配置文件中学习率机制是steplr，初始lr是0.1，非常大，且gamma是1.0，保持不变。为啥代码中花游poly的学习率？
2. 比如我的训练集全部都是256*256的图 ，如果我resize=224，那么crop_range是相当于256*crop_range[0]>224？

**Comment by cavalleria** [comment]
1.poly
2.random_crop--> resize

**Comment by zhangyunming** [comment]
好的，谢谢

**Comment by zhangyunming** [comment]
你好，
1. 你用的mobile2的pretrained model是哪个啊？能否给出地址或是链接
2. 关于mask光流跟踪的问题，大致原理是怎样的，稳了但是拖影如何解决？
